### ISSUE TITLE
License

### ISSUE THREAD

**Issue by namestise** [reowen/Stata#1]
@reowen

Can you please include the license. 

I would like to use this for my teaching source

**Comment by reowen** [comment]
Do you mean the Stata version? This was all in Stata 12. Or do you mean just permission to use the code? Feel free to use the code for your class. I have no problems with that. No need to cite me or anything

**Comment by namestise** [comment]
@reowen Thanks

I mean your code license

https://github.com/blog/1530-choosing-an-open-source-license

**Comment by reowen** [comment]
Sorry for the very long delay, but the code license has just been added.
